### PR TITLE
Create I2DVpQ.dart

### LINKED ISSUE #224: [Dart] [very_easy] Create a Dart program to count the occurrences of a specific word in a sentence.
# Question : Create a Dart program to count the occurrences of a specific word in a sentence. 
Path to create the file : `JaFfnJ/I2DVpQ.dart`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by 457ayan**
# 📑 DESCRIPTION

Issue Number : #224 
### ❓ What has been changed : 

Fixes #224

### CODE REVIEW

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Review by 457ayan — COMMENTED** [review]
check this

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
patch-2

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
