### PR TITLE
Create 9N773k.js

### LINKED ISSUE #405: [JavaScript] [medium] Write a JavaScript program to check if a given binary tree is a valid binary search tree (BST).
# Question : Write a JavaScript program to check if a given binary tree is a valid binary search tree (BST). 
Path to create the file : `EJ7FvD/9N773k.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by githubuser16384**
# 📑 DESCRIPTION

Issue Number : #405
### ❓ What has been changed : 

Fixes #405

### CODE REVIEW

**Comment by githubuser16384** [comment]
!check

**Comment by githubuser16384** [comment]
!check

**Comment by githubuser16384** [comment]
!check

**Comment by githubuser16384** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
