### PR TITLE
Create ZpQ0RY.rb

### LINKED ISSUE #264: [Ruby] [easy] Calculate the perimeter of a rectangle.
# Question : Calculate the perimeter of a rectangle. 
Path to create the file : `rn4rBK/ZpQ0RY.rb`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by HarshitVashisht11**
# 📑 DESCRIPTION

Issue Number : #264 
### ❓ What has been changed :  Create a program in Ruby to calculate perimeter of rectangle

Fixes #264

Fixes #264

### CODE REVIEW

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
