### PR TITLE
Create 9tL863.cs

### LINKED ISSUE #32: [C#] [hard] Implement a basic compiler for a custom programming language.
# Question : Implement a basic compiler for a custom programming language. 
Path to create the file : `S8yrWM/9tL863.cs`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by raj19344**
# 📑 DESCRIPTION

Issue Number : #32
### ❓ What has been changed : 

Fixes #32

### CODE REVIEW

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
> Seems like you haven't completed Task 2 follow @CodingWithHardik to complete Task 2

I already follow @CodingWithHardik , kindly allow me in next stage

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
