### PR TITLE
Create oY21fr.cpp

### LINKED ISSUE #229: [C++] [medium] Write a program to check if a number is a powerful number.
# Question : Write a program to check if a number is a powerful number. 
Path to create the file : `g0CbpW/oY21fr.cpp`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by 457ayan**
# 📑 DESCRIPTION

Issue Number : #229 
### ❓ What has been changed : check stronger number get input and recive output

Fixes #229

### CODE REVIEW

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Comment by 457ayan** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
