### PR TITLE
Create iiPhyY.java

### LINKED ISSUE #134: [Java] [easy] Implement a program to transpose a 2D array (matrix).
# Question : Implement a program to transpose a 2D array (matrix). 
Path to create the file : `yDrl2a/iiPhyY.java`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by rahmani3101**
# 📑 DESCRIPTION

Issue Number : #134
### ❓ What has been changed : 

Fixes #134

Fixes #134

### CODE REVIEW

**Comment by rahmani3101** [comment]
!check

**Comment by rahmani3101** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
