### PR TITLE
Create QQiFak.java

### LINKED ISSUE #349: [Java] [easy] Create a program that calculates and prints the volume of a cylinder with user-provided radius and height.
# Question : Create a program that calculates and prints the volume of a cylinder with user-provided radius and height. 
Path to create the file : `xyxgDc/QQiFak.java`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by agaramudhala**
# 📑 DESCRIPTION

Issue Number : #349
### ❓ What has been changed : 

Fixes #349

Fixes #349

### CODE REVIEW

**Comment by agaramudhala** [comment]
!check

**Comment by agaramudhala** [comment]
!check

**Comment by agaramudhala** [comment]
hi @siddharth7000 @CodingWithHardik , kindly review and merge if it looks okay

**Comment by agaramudhala** [comment]
hi @siddharth7000 @CodingWithHardik , kindly review and merge if it looks okay

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
