### PR TITLE
Create 2cGQiK.php

### LINKED ISSUE #226: [PHP] [medium] Create a PHP script that implements basic URL redirection.
# Question : Create a PHP script that implements basic URL redirection. 
Path to create the file : `L3SpcJ/2cGQiK.php`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by AvinashAnand02**
# 📑 DESCRIPTION

Issue Number : #226
### ❓ What has been changed : 

Fixes #226

Fixes #226

### CODE REVIEW

**Comment by AvinashAnand02** [comment]
!check

**Comment by AvinashAnand02** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
