### PR TITLE
Create 080Ipo.cs

### LINKED ISSUE #45: [C#] [easy] Calculate the area of a sector of a circle.
# Question : Calculate the area of a sector of a circle. 
Path to create the file : `B9ORbH/080Ipo.cs`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Neelyooo**
# 📑 DESCRIPTION

Issue Number : #45 
### ❓ What has been changed : 

Fixes #45

Fixes #45

### CODE REVIEW

**Comment by Neelyooo** [comment]
!check

**Comment by Neelyooo** [comment]
!check

**Comment by Neelyooo** [comment]
!check

**Comment by Neelyooo** [comment]
!check

**Comment by Neelyooo** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
