### PR TITLE
Create UEuD45.dart

### LINKED ISSUE #19: [Dart] [easy] Create a Dart class named Person with properties for name, age, and city. Instantiate an object of this class and print out the person's details.
# Question : Create a Dart class named Person with properties for name, age, and city. Instantiate an object of this class and print out the person's details. 
Path to create the file : `7rJDo7/UEuD45.dart`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by ashwani798**
# 📑 DESCRIPTION

Issue Number : #19
### ❓ What has been changed : 

Fixes #19

Fixes #19

### CODE REVIEW

**Comment by ashwani798** [comment]
!check

**Comment by ashwani798** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
