### PR TITLE
Written the script  3nwjnB.sh

### LINKED ISSUE #403: [Shell] [hard] Write a script that monitors DNS requests and responses for suspicious activity and logs the results.
# Question : Write a script that monitors DNS requests and responses for suspicious activity and logs the results. 
Path to create the file : `60KHS8/3nwjnB.sh`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Sarthak027**
# 📑 DESCRIPTION

Issue Number : #403 
### ❓ What has been changed : 
written  the shell script in the given path 60KHS8/3nwjnB.sh

Fixes #403

Fixes #403

### CODE REVIEW

**Comment by Sarthak027** [comment]
!check

**Comment by Sarthak027** [comment]
!check

**Comment by Sarthak027** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
