### PR TITLE
Create meaHEQ.kt

### LINKED ISSUE #323: [Kotlin] [medium] Create a program to find the maximum subarray sum in an array using the Kadane's algorithm in Kotlin.
# Question : Create a program to find the maximum subarray sum in an array using the Kadane's algorithm in Kotlin. 
Path to create the file : `q6Koqe/meaHEQ.kt`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by ghostrider45**
# 📑 DESCRIPTION

Issue Number : #323
### ❓ What has been changed : 

Fixes #323

Fixes #323

### CODE REVIEW

**Comment by ghostrider45** [comment]
!check

**Comment by ghostrider45** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
