### PR TITLE
Create wiXGks.js

### LINKED ISSUE #1120: [JavaScript] [hard] Write a JavaScript program to solve the Traveling Salesman Problem (TSP) using a dynamic programming approach.
# Question : Write a JavaScript program to solve the Traveling Salesman Problem (TSP) using a dynamic programming approach. 
Path to create the file : `VdtTUY/wiXGks.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by vibhamishra07**
# 📑 DESCRIPTION

Issue Number : #1120
### ❓ What has been changed : 

Fixes #1120

Fixes #1120

### CODE REVIEW

**Comment by vibhamishra07** [comment]
!check

**Comment by vibhamishra07** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
