### PR TITLE
Create KJxFoc.php

### LINKED ISSUE #102: [PHP] [easy] Create a PHP script to calculate and display the difference between two dates.
# Question : Create a PHP script to calculate and display the difference between two dates. 
Path to create the file : `bij2Ti/KJxFoc.php`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Neelyooo**
# 📑 DESCRIPTION

Issue Number : #102 
### ❓ What has been changed : 

Fixes #102

Fixes #102

### CODE REVIEW

**Comment by Neelyooo** [comment]
!check

**Comment by Neelyooo** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
