### PR TITLE
Create 8pHwcI.rs

### LINKED ISSUE #231: [Rust] [medium] Create a program that simulates a basic restaurant ordering system with menus, orders, and bills.
# Question : Create a program that simulates a basic restaurant ordering system with menus, orders, and bills. 
Path to create the file : `Tss52L/8pHwcI.rs`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by OhmRamwala**
# 📑 DESCRIPTION

Issue Number : #231
### ❓ What has been changed : Wrote a few lines of code

Fixes #231

Fixes #231

### CODE REVIEW

**Comment by OhmRamwala** [comment]
!check

**Comment by OhmRamwala** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
