### PR TITLE
Added Javascript

### LINKED ISSUE #13: [JavaScript] [medium] Write a JavaScript program to find the shortest common superstring of a given set of strings.
# Question : Write a JavaScript program to find the shortest common superstring of a given set of strings. 
Path to create the file : `9i8anZ/WVF7Pk.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by akadeepesh**
added a JavaScript program to find the shortest common superstring of a given set of strings.

# 📑 DESCRIPTION

Issue Number : #13 
### ❓ What has been changed : 
Added a JavaScript program to find the shortest common superstring of a given set of strings.

Fixes #13

Fixes #13

### CODE REVIEW

**Comment by akadeepesh** [comment]
!check

**Comment by akadeepesh** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
