### PR TITLE
Create 5Oi5Ym.java

### LINKED ISSUE #426: [Java] [extreme_hard] Write a program that uses Java's JCA to implement custom secure communication protocols for space-based communication systems.
# Question : Write a program that uses Java's JCA to implement custom secure communication protocols for space-based communication systems. 
Path to create the file : `MtTack/5Oi5Ym.java`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by pedropietro**
This is a basic example, and in a real-world space-based communication system, you'd need to consider many other factors like error-correction, handling lost packets, and more. Also, while RSA is used here for key exchange, in a more practical setup, you might want to use a protocol like Diffie-Hellman or ECDH for key exchange.

# 📑 DESCRIPTION

Creating a custom secure communication protocol using Java's JCA (Java Cryptography Architecture) is a complex task and requires careful consideration of various factors. Here's a basic outline, followed by a simple implementation:

Outline:

Define the requirements: What are the security requirements? What type of encryption is needed? Do we need authentication, integrity, and confidentiality?
Key management: How are keys generated, distributed, and stored?
Message format: How are messages structured? This can include headers, body, and footers.
Implementation: Use JCA to implement the encryption, decryption, and other cryptographic operations.
Example Implementation:

For simplicity, we'll create a program that:

Uses RSA for key exchange.
Uses AES for message encryption and decryption.
Has a simple message format: [encrypted AES key][encrypted message].

Issue Number : #426
### ❓ What has been changed : 

Fixes #426

Fixes #426

### CODE REVIEW

**Comment by pedropietro** [comment]
!check

**Comment by pedropietro** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
