### PR TITLE
Create ENvjG2.cpp

### LINKED ISSUE #406: [C++] [easy] Find the sum of the series: 1^2 + 2^2 + 3^2 + ... + n^2.
# Question : Find the sum of the series: 1^2 + 2^2 + 3^2 + ... + n^2. 
Path to create the file : `9Oonsw/ENvjG2.cpp`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by khushisaxena17**
# 📑 DESCRIPTION

Issue Number : #406
### ❓ What has been changed : 

Fixes #406

Fixes #406

### CODE REVIEW

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Pull request merged**
