### PR TITLE
Create AuNoEo.cs

### LINKED ISSUE #475: [C#] [easy] Calculate the surface area of a cylinder.
# Question : Calculate the surface area of a cylinder. 
Path to create the file : `uQYSrA/AuNoEo.cs`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by pedropietro**
# 📑 DESCRIPTION
Calculate the surface area of a cylinder. 
Surface Area=2πr 
2
 +2πrh
Where:

�
r is the radius of the base of the cylinder.
ℎ
h is the height of the cylinder.
�
π is approximately 3.14159.

Issue Number : #475
### ❓ What has been changed : 

Fixes #475

Fixes #475

### CODE REVIEW

**Comment by pedropietro** [comment]
!check

**Comment by pedropietro** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
