### PR TITLE
Create V2NKuG.go

### LINKED ISSUE #190: [Go] [very_easy] Implement a program that finds the second largest element in an array.
# Question : Implement a program that finds the second largest element in an array. 
Path to create the file : `WK1Dt8/V2NKuG.go`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Able2002**
# 📑 DESCRIPTION

Issue Number : #190
### ❓ What has been changed : 

Fixes #190

Fixes #190

### CODE REVIEW

**Comment by Able2002** [comment]
!check

**Comment by Able2002** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
