### PR TITLE
Create R06tAd.dart

### LINKED ISSUE #308: [Dart] [easy] Implement a Dart class named BankAccount with properties for accountNumber, accountHolder, and balance. Add methods to deposit and withdraw money from the account, and print the account details.
# Question : Implement a Dart class named BankAccount with properties for accountNumber, accountHolder, and balance. Add methods to deposit and withdraw money from the account, and print the account details. 
Path to create the file : `VnJEmW/R06tAd.dart`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Krrishn07**
# 📑 DESCRIPTION

Issue Number : #308
### ❓ What has been changed : 

Fixes #308

Fixes #308

### CODE REVIEW

**Comment by Krrishn07** [comment]
!check

**Comment by Krrishn07** [comment]
!check

**Comment by Krrishn07** [comment]
!check

**Comment by Krrishn07** [comment]
!check

**Comment by Krrishn07** [comment]
!check

**Comment by Krrishn07** [comment]
!check

**Comment by Krrishn07** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
