### PR TITLE
[JavaScript] convert a string to uppercase

### LINKED ISSUE #87: [JavaScript] [very_easy] Convert a string to uppercase.
# Question : Convert a string to uppercase. 
Path to create the file : `X5aLGr/hn89EV.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by bkpecho**
# 📑 DESCRIPTION

Issue Number : #87 
### ❓ What has been changed : 
Created hn89EV.js that converts a string to uppercase using JavaScript

Fixes #87

Fixes #87

### CODE REVIEW

**Comment by bkpecho** [comment]
!check

**Comment by bkpecho** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
