### PR TITLE
Create Ktr5LR.java

### LINKED ISSUE #103: [Java] [medium] Implement a binary search algorithm to find a specific element in an array of integers.
# Question : Implement a binary search algorithm to find a specific element in an array of integers. 
Path to create the file : `7twFw1/Ktr5LR.java`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Sidd7000**
# 📑 DESCRIPTION

Issue Number : #103
### ❓ What has been changed : 

Fixes #103

Fixes #103

### CODE REVIEW

**Comment by Sidd7000** [comment]
!check

**Review by siddharth7000 — APPROVED** [review]
Good

**Comment by siddharth7000** [comment]
!accept

**Comment by CodingWithHardik** [comment]
!accept

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
