### PR TITLE
added CyP5vx/jPawXX.dart

### LINKED ISSUE #365: [Dart] [very_easy] Create a Dart program to find the LCM (Least Common Multiple) of two numbers.
# Question : Create a Dart program to find the LCM (Least Common Multiple) of two numbers. 
Path to create the file : `CyP5vx/jPawXX.dart`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by vivekPatil45**
# 📑 DESCRIPTION

Issue Number : #365
### ❓ What has been changed : 
Fixes : #365

Fixes #365

### CODE REVIEW

**Comment by vivekPatil45** [comment]
!check

**Comment by vivekPatil45** [comment]
!check

**Comment by vivekPatil45** [comment]
!check

**Comment by vivekPatil45** [comment]
!check

**Comment by vivekPatil45** [comment]
!check

**Comment by vivekPatil45** [comment]
I am follow @CodingWithHardik

**Comment by vivekPatil45** [comment]
!check

**Comment by vivekPatil45** [comment]
!check

**Comment by vivekPatil45** [comment]
!check

**Comment by vivekPatil45** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
