### PR TITLE
Create Ry8L40.py

### LINKED ISSUE #256: [Python] [easy] Calculate the sum of two integers and print the result.
# Question : Calculate the sum of two integers and print the result. 
Path to create the file : `FpXM1T/Ry8L40.py`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Sarnendu-Paul**
# 📑 DESCRIPTION

Issue Number : #256 
### ❓ What has been changed : Wrote a code to take 2 integers from user and calculate the sum and print the result.

Fixes #256

Fixes #256

### CODE REVIEW

**Comment by Sarnendu-Paul** [comment]
!check

**Comment by Sarnendu-Paul** [comment]
!check

**Comment by Sarnendu-Paul** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
