### PR TITLE
Added js function to find the sum of even numbers from 1 to 20.

### LINKED ISSUE #127: [JavaScript] [very_easy] Calculate the sum of even numbers from 1 to 20.
# Question : Calculate the sum of even numbers from 1 to 20. 
Path to create the file : `uuFUAe/orqeEG.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Virtual4087**
Issue Number : #127
Created a JS file to find the sum of even numbers from 1 to 20.

Fixes #127

Fixes #127

### CODE REVIEW

**Comment by Virtual4087** [comment]
!check

**Comment by Virtual4087** [comment]
!check

**Comment by Virtual4087** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
