### PR TITLE
Create 8s3FDm.py

### LINKED ISSUE #109: [Python] [very_easy] Create a function to check if a string contains only digits.
# Question : Create a function to check if a string contains only digits. 
Path to create the file : `wSpIt2/8s3FDm.py`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by siddharthsingh101**
# 📑 DESCRIPTION

Issue Number : #109
### ❓ What has been changed : 

Fixes #109

Fixes #109

### CODE REVIEW

**Comment by siddharthsingh101** [comment]
!check

**Comment by siddharthsingh101** [comment]
!check

**Review by Sidd7000 — APPROVED** [review]
Great
Subscribe ```CLoudhustlers``` for more content.

**Review by siddharth7000 — APPROVED** [review]
Great

**Comment by siddharth7000** [comment]
!accept

**Pull request merged**
