### PR TITLE
Create qSQJpB.sh

### LINKED ISSUE #249: [Shell] [hard] Create a script that monitors and analyzes logs from multiple servers to detect and report on security incidents.
# Question : Create a script that monitors and analyzes logs from multiple servers to detect and report on security incidents. 
Path to create the file : `A4gJYy/qSQJpB.sh`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by HarshitVashisht11**
# 📑 DESCRIPTION

Issue Number : #249 
### ❓ What has been changed : 

Fixes #249

Fixes #249

### CODE REVIEW

**Comment by HarshitVashisht11** [comment]
! check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
i have already followed him but still getting error

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
