### PR TITLE
Create 6fZ3mN.c

### LINKED ISSUE #356: [C] [easy] Write a program to sort an array in descending order.
# Question : Write a program to sort an array in descending order. 
Path to create the file : `FRls6W/6fZ3mN.c`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by jyotibhatt827**
# 📑 DESCRIPTION

Issue Number : #356
### ❓ What has been changed : 

Fixes #356

### CODE REVIEW

**Comment by jyotibhatt827** [comment]
!check

**Comment by jyotibhatt827** [comment]
!check

**Comment by jyotibhatt827** [comment]
!check

**Comment by jyotibhatt827** [comment]
!check

**Comment by jyotibhatt827** [comment]
!check

**Comment by jyotibhatt827** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
