### PR TITLE
Create sT4Wkj.sh

### LINKED ISSUE #404: [Shell] [very_easy] Create a script to find and display the oldest file in a directory.
# Question : Create a script to find and display the oldest file in a directory. 
Path to create the file : `iApXYs/sT4Wkj.sh`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by pedropietro**
[Shell] [very_easy] Create a script to find and display the oldest file in a directory. #404 Issues Number: #404

# 📑 DESCRIPTION
Here's how to use the script:

Save the above script to a file, say sT4Wkj.sh.
Make the script executable using the command: chmod +x sT4Wkj.sh
Run the script with the desired directory as an argument: ./sT4Wkj.sh /path/to/directory
The script will then display the oldest file in the specified directory. If there are no files in the directory or the directory doesn't exist, appropriate messages will be displayed.

Issue Number : #404
### ❓ What has been changed : 

Fixes #404

Fixes #404

### CODE REVIEW

**Comment by pedropietro** [comment]
!check

**Comment by pedropietro** [comment]
!check

**Comment by pedropietro** [comment]
!assign

**Comment by pedropietro** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
