### PR TITLE
CRUD using php

### LINKED ISSUE #443: [PHP] [easy] Implement a simple CRUD (Create, Read, Update, Delete) system for a list of items.
# Question : Implement a simple CRUD (Create, Read, Update, Delete) system for a list of items. 
Path to create the file : `oy6RH3/D79t64.php`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by PSYCHNERD2512**
# 📑 DESCRIPTION

Issue Number : #443 
### ❓ What has been changed : 
CRUD implemented using php.

Fixes #443

Fixes #443

### CODE REVIEW

**Comment by PSYCHNERD2512** [comment]
!check

**Comment by PSYCHNERD2512** [comment]
!check

**Comment by PSYCHNERD2512** [comment]
!check

**Comment by PSYCHNERD2512** [comment]
!check

**Comment by PSYCHNERD2512** [comment]
!check

**Comment by PSYCHNERD2512** [comment]
!check

**Comment by PSYCHNERD2512** [comment]
!check

**Comment by PSYCHNERD2512** [comment]
!check

**Comment by PSYCHNERD2512** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
