### PR TITLE
Create gq4rkd.c

### LINKED ISSUE #29: [C] [easy] Implement a program to calculate the power of a number using a loop.
# Question : Implement a program to calculate the power of a number using a loop. 
Path to create the file : `4UA7ej/gq4rkd.c`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Neelyooo**
# 📑 DESCRIPTION

Issue Number : #29
### ❓ What has been changed : Wrote a C program to implement the power of the number.

Fixes #29

Fixes #29

### CODE REVIEW

**Comment by Neelyooo** [comment]
!check

**Comment by Neelyooo** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
