### PR TITLE
Create qyGvE2.go

### LINKED ISSUE #38: [Go] [medium] Write a program that simulates a basic blogging platform with functions for creating and managing blog posts.
# Question : Write a program that simulates a basic blogging platform with functions for creating and managing blog posts. 
Path to create the file : `xybMwY/qyGvE2.go`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by chandanmahato624**
# 📑 DESCRIPTION

Issue Number : #38
### ❓ What has been changed : 

Fixes #38

Fixes #38

### CODE REVIEW

**Comment by chandanmahato624** [comment]
!check

**Comment by chandanmahato624** [comment]
!check

**Comment by chandanmahato624** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!acccept

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
