### PR TITLE
Factorial issue: #129

### LINKED ISSUE #129: [Python] [very_easy] Calculate the factorial of a number.
# Question : Calculate the factorial of a number. 
Path to create the file : `hCBMb3/PgvAXx.py`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Mostaxd**
# 📑 DESCRIPTION
Issue Number : #129 
### ❓ What has been changed : 
Fixes #129 

Fixes #129

Fixes #129

### CODE REVIEW

**Comment by Mostaxd** [comment]
!check

**Comment by Mostaxd** [comment]
!check

**Comment by CodingWithHardik** [comment]
file is empty

**Comment by Mostaxd** [comment]
> file is empty add your code and request for review

@CodingWithHardik 
Click on the 3 dots, and then on "View file" if you view it directly from the browser.

**Review by Mostaxd — COMMENTED** [review]
Click on the 3 dots, and then on "View file" if you view it directly from the browser.

**Comment by CodingWithHardik** [comment]
please open a pull request with master branch or watch cloud hustlers video

**Pull request closed without merging**
