### PR TITLE
Create BRRbEj.c

### LINKED ISSUE #334: [C] [medium] Create a program to add two binary numbers using functions.
# Question : Create a program to add two binary numbers using functions. 
Path to create the file : `DFGHcY/BRRbEj.c`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by AniruddhaFalke**
# 📑 DESCRIPTION

Issue Number : #334
### ❓ What has been changed : 

Fixes #334

Fixes #334

### CODE REVIEW

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check.

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Comment by AniruddhaFalke** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
