### PR TITLE
Create rMH83q.js

### LINKED ISSUE #362: [JavaScript] [hard] Write a JavaScript program to implement a basic consensus algorithm such as Algorand for a distributed ledger.
# Question : Write a JavaScript program to implement a basic consensus algorithm such as Algorand for a distributed ledger. 
Path to create the file : `UC1orM/rMH83q.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by TayyabHussain03**
# 📑 DESCRIPTION

Issue Number : #362
### ❓ What has been changed : 

Fixes #362

Fixes #362

### CODE REVIEW

**Comment by TayyabHussain03** [comment]
!check

**Comment by TayyabHussain03** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
