### PR TITLE
Create XmYQZi.sh

### LINKED ISSUE #86: [Shell] [hard] Write a script that analyzes network traffic patterns to detect and mitigate network intrusions.
# Question : Write a script that analyzes network traffic patterns to detect and mitigate network intrusions. 
Path to create the file : `34BRa0/XmYQZi.sh`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by ArpanLeedan**
# 📑 DESCRIPTION

Issue Number : #86
### ❓ What has been changed : 

Fixes #86

Fixes #86

### CODE REVIEW

**Comment by ArpanLeedan** [comment]
!check

**Comment by ArpanLeedan** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
