### PR TITLE
Create 2CmJI9.c

### LINKED ISSUE #341: [C] [hard] Implement a program to solve the Knapsack problem using dynamic programming.
# Question : Implement a program to solve the Knapsack problem using dynamic programming. 
Path to create the file : `Pidtnr/2CmJI9.c`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by SonjeVilas**
# 📑 DESCRIPTION

Issue Number : #341
### ❓ What has been changed : 

Fixes #341

### CODE REVIEW

**Comment by SonjeVilas** [comment]
!check

> Seems like you haven't completed Task 2 follow @CodingWithHardik to complete Task 2

**Comment by SonjeVilas** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
