### PR TITLE
Create 5iQvYz.go

### LINKED ISSUE #350: [Go] [easy] Create a Go program that calculates the sum of all prime numbers up to a specified limit.
# Question : Create a Go program that calculates the sum of all prime numbers up to a specified limit. 
Path to create the file : `Ueshhq/5iQvYz.go`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by souvikpramanikgit**
# 📑 DESCRIPTION

Issue Number : #350
### ❓ What has been changed : 

Fixes #350

Fixes #350

### CODE REVIEW

**Comment by souvikpramanikgit** [comment]
!check

**Comment by souvikpramanikgit** [comment]
!check

**Comment by souvikpramanikgit** [comment]
!check

**Comment by souvikpramanikgit** [comment]
But i follow him

**Comment by souvikpramanikgit** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
