### PR TITLE
Create baZZwE.kt

### LINKED ISSUE #96: [Kotlin] [very_easy] Create a program to check if a number is a happy number in Kotlin.
# Question : Create a program to check if a number is a happy number in Kotlin. 
Path to create the file : `7u4Aw0/baZZwE.kt`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Seventy7dot2**
# 📑 DESCRIPTION
Issue Number : #96  

Fixes #96

Fixes #96

### CODE REVIEW

**Comment by Seventy7dot2** [comment]
!check

**Comment by Seventy7dot2** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
