### PR TITLE
Create nmX1Kw.ts

### LINKED ISSUE #21: [TypeScript] [medium] Create a TypeScript function to implement a binary search algorithm for a sorted array.
# Question : Create a TypeScript function to implement a binary search algorithm for a sorted array. 
Path to create the file : `MBABSl/nmX1Kw.ts`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Aeromaster213**
# 📑 DESCRIPTION

Issue Number : #21 
### ❓ What has been changed :  Created the BinarySearch Algo in TypeScript

Fixes #21

Fixes #21

### CODE REVIEW

**Comment by Aeromaster213** [comment]
!check

**Comment by Aeromaster213** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
