### PR TITLE
Create rBACti.js

### LINKED ISSUE #287: [JavaScript] [extreme_hard] Write a JavaScript program to find the largest known prime number using a quantum computer with a quantum-enhanced search algorithm.
# Question : Write a JavaScript program to find the largest known prime number using a quantum computer with a quantum-enhanced search algorithm. 
Path to create the file : `aNxgy9/rBACti.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by SonjeVilas**
# 📑 DESCRIPTION

Issue Number : #287
### ❓ What has been changed : 

Fixes #287

### CODE REVIEW

**Comment by SonjeVilas** [comment]
!check

**Comment by SonjeVilas** [comment]
!check

**Comment by SonjeVilas** [comment]
!check

**Comment by SonjeVilas** [comment]
!check

**Comment by SonjeVilas** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
