### PR TITLE
Create joXgtn.swift

### LINKED ISSUE #376: [Swift] [medium] Create a Swift program to check if a number is an Armstrong number.
# Question : Create a Swift program to check if a number is an Armstrong number. 
Path to create the file : `30Q9G0/joXgtn.swift`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by sammyifelse**
# 📑 DESCRIPTION

Issue Number : #376 
### ❓ What has been changed : 

Fixes #376

Fixes #376

### CODE REVIEW

**Comment by sammyifelse** [comment]
!check

**Comment by sammyifelse** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
