### PR TITLE
Create fbw33v.dart

### LINKED ISSUE #268: [Dart] [medium] Create a Dart class representing a contact management system with methods for adding, updating, and searching for contacts.
# Question : Create a Dart class representing a contact management system with methods for adding, updating, and searching for contacts. 
Path to create the file : `symjq1/fbw33v.dart`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Sarthakcried**
# 📑 DESCRIPTION

Issue Number : #268
### ❓ What has been changed : 

Fixes #268

Fixes #268

### CODE REVIEW

**Comment by Sarthakcried** [comment]
!check

**Comment by Sarthakcried** [comment]
I have followed CodingwithHardik still the task is not completing

**Comment by Sarthakcried** [comment]
help

**Comment by Sarthakcried** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
