### PR TITLE
Create YlBiNq.rb

### LINKED ISSUE #240: [Ruby] [medium] Implement a basic web scraping tool to extract data from a website.
# Question : Implement a basic web scraping tool to extract data from a website. 
Path to create the file : `kPx8vl/YlBiNq.rb`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by priyanujbd23**
# 📑 DESCRIPTION

Issue Number : #240
### ❓ What has been changed : 

Fixes #240

Fixes #240

### CODE REVIEW

**Comment by priyanujbd23** [comment]
!check

**Comment by priyanujbd23** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
