### PR TITLE
Create Ge4fXc.java

### LINKED ISSUE #116: [Java] [easy] Implement a program to find and print the index of the first occurrence of a substring in a string.
# Question : Implement a program to find and print the index of the first occurrence of a substring in a string. 
Path to create the file : `v17nds/Ge4fXc.java`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by charandeepsinghb**
# 📑 DESCRIPTION

Issue Number : #116
### ❓ What has been changed : 
Added a program to find and print the index of the first occurrence of a substring in a string in java.

Fixes #116

Fixes #116

### CODE REVIEW

**Comment by charandeepsinghb** [comment]
!check

**Comment by charandeepsinghb** [comment]
!check

**Comment by charandeepsinghb** [comment]
!check

**Review by CodingWithHardik — CHANGES_REQUESTED** [review]
`v17nds/Ge4fXc.class` remove this file

**Comment by CodingWithHardik** [comment]
remove  `v17nds/Ge4fXc.class` file

**Comment by charandeepsinghb** [comment]
Removed v17nds/Ge4fXc.class file

**Comment by charandeepsinghb** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]

**Comment by CodingWithHardik** [comment]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
