### PR TITLE
Create 1g6wI3.cpp

### LINKED ISSUE #271: [C++] [hard] Implement a C++ function to calculate the longest common prefix of an array of strings using binary search.
# Question : Implement a C++ function to calculate the longest common prefix of an array of strings using binary search. 
Path to create the file : `Q1PU1i/1g6wI3.cpp`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by HarshitVashisht11**
# 📑 DESCRIPTION

Issue Number : #271 
### ❓ What has been changed : 

Fixes #271

Fixes #271

### CODE REVIEW

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!status

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Comment by HarshitVashisht11** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
