### PR TITLE
Create s9cSFx.cs

### LINKED ISSUE #69: [C#] [very_easy] Calculate the sum of all even numbers from 1 to 100.
# Question : Calculate the sum of all even numbers from 1 to 100. 
Path to create the file : `Lzurrp/s9cSFx.cs`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by I-sandesh**
# 📑 DESCRIPTION

Issue Number : #69
### ❓ What has been changed : 

Fixes #69

Fixes #69

### CODE REVIEW

**Comment by I-sandesh** [comment]
!check

**Comment by I-sandesh** [comment]
!check

**Comment by I-sandesh** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
