### PR TITLE
Create 9LErXG.js

### LINKED ISSUE #442: [JavaScript] [hard] Write a JavaScript program to implement a basic distributed key-value store with consistency guarantees.
# Question : Write a JavaScript program to implement a basic distributed key-value store with consistency guarantees. 
Path to create the file : `wwNYEJ/9LErXG.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by aadrshkashyp**
# 📑 DESCRIPTION

Issue Number : #442
### ❓ What has been changed : 

Fixes #442

Fixes #442

### CODE REVIEW

**Comment by aadrshkashyp** [comment]
!check

**Comment by aadrshkashyp** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
