### PR TITLE
Create uDbpj1.go

### LINKED ISSUE #338: [Go] [easy] Create a Go program that calculates the area of a hexagon.
# Question : Create a Go program that calculates the area of a hexagon. 
Path to create the file : `Y7BKc1/uDbpj1.go`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by saai07**
# 📑 DESCRIPTION

Issue Number : #338
### ❓ What has been changed : 

Fixes #338

### CODE REVIEW

**Comment by saai07** [comment]
!check

**Comment by saai07** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
