### PR TITLE
Create I7wkdc.ts

### PR DESCRIPTION
**Pull request by SrijaAdhya12**
# 📑 DESCRIPTION

Issue Number : #10

### CODE REVIEW

**Comment by CodingWithHardik** [comment]
Star this repo and comment `!check` to check if the task is completed.

**Comment by SrijaAdhya12** [comment]
!check

**Comment by SrijaAdhya12** [comment]
!check

**Comment by SrijaAdhya12** [comment]
!check

**Comment by SrijaAdhya12** [comment]
!check

**Comment by SrijaAdhya12** [comment]
!check

**Comment by SrijaAdhya12** [comment]
!check

**Comment by SrijaAdhya12** [comment]
!check

**Comment by SrijaAdhya12** [comment]
!check

**Comment by SrijaAdhya12** [comment]
!check

**Comment by CodingWithHardik** [comment]
Hey it's a bug just skip we will approve your request

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
