### PR TITLE
Create r9dyn1.java

### LINKED ISSUE #48: [Java] [extreme_hard] Create a custom Java-based framework for developing virtual reality (VR) applications and experiences.
# Question : Create a custom Java-based framework for developing virtual reality (VR) applications and experiences. 
Path to create the file : `z3vKY3/r9dyn1.java`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by raj19344**
# 📑 DESCRIPTION

Issue Number : #48
### ❓ What has been changed : 

Fixes #48

### CODE REVIEW

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
> Seems like you haven't completed Task 2 follow @CodingWithHardik to complete Task 2

I followed the @CodingWithHardik but it shows that you haven't follow kindly solve this issue
Screenshot (533)

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
