### PR TITLE
Create ShhJOk.java

### LINKED ISSUE #80: [Java] [hard] Create a program that uses Java's CompletableFuture to implement a parallel web scraper.
# Question : Create a program that uses Java's CompletableFuture to implement a parallel web scraper. 
Path to create the file : `lmXHtR/ShhJOk.java`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Debashis-11101-srijib**
# 📑 DESCRIPTION

Issue Number : #80 
### ❓ What has been changed : 

Fixes #80

Fixes #80

### CODE REVIEW

**Comment by Debashis-11101-srijib** [comment]
!check

**Comment by Debashis-11101-srijib** [comment]
!check

**Comment by Debashis-11101-srijib** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
