### PR TITLE
Create raZGey.js

### LINKED ISSUE #195: [JavaScript] [medium] Write a JavaScript program to find the longest substring without repeating characters in a given string.
# Question : Write a JavaScript program to find the longest substring without repeating characters in a given string. 
Path to create the file : `H4ChHM/raZGey.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Rahul-Roy-Hub**
# 📑 DESCRIPTION

Issue Number : #195
### ❓ What has been changed : 

Fixes #195

Fixes #195

### CODE REVIEW

**Comment by Rahul-Roy-Hub** [comment]
!check

**Comment by Rahul-Roy-Hub** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
