### PR TITLE
Create rTbcT9.c

### LINKED ISSUE #46: [C] [extreme_hard] Create a program to perform real-time gesture recognition for augmented reality applications.
# Question : Create a program to perform real-time gesture recognition for augmented reality applications. 
Path to create the file : `pMTwl5/rTbcT9.c`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by raj19344**
# 📑 DESCRIPTION

Issue Number : #46
### ❓ What has been changed : 

Fixes #46

### CODE REVIEW

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check

**Comment by raj19344** [comment]
!check
Screenshot (533)

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
