### PR TITLE
Create OtcRPT.ts

### LINKED ISSUE #151: [TypeScript] [hard] Implement a TypeScript function to simulate the behavior of a complex autonomous system (e.g., self-driving cars, drones).
# Question : Implement a TypeScript function to simulate the behavior of a complex autonomous system (e.g., self-driving cars, drones). 
Path to create the file : `MebW50/OtcRPT.ts`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by kumartusha**
# 📑 DESCRIPTION

Issue Number : #151
### ❓ What has been changed : 

Fixes #151

Fixes #151

### CODE REVIEW

**Comment by kumartusha** [comment]
!check

**Comment by kumartusha** [comment]
!check

**Comment by kumartusha** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
