### PR TITLE
Create eBouvx.dart

### LINKED ISSUE #146: [Dart] [very_easy] Calculate the area of a trapezium in Dart given its bases and height.
# Question : Calculate the area of a trapezium in Dart given its bases and height. 
Path to create the file : `gWXnrb/eBouvx.dart`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Devanshgupta2004**
# 📑 DESCRIPTION

Issue Number : #146
### ❓ What has been changed : 

Fixes #146

Fixes #146

### CODE REVIEW

**Comment by Devanshgupta2004** [comment]
!check

**Comment by Devanshgupta2004** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
