### PR TITLE
Create xC6lTa.rs

### LINKED ISSUE #51: [Rust] [hard] Implement a Rust program to perform real-time natural language translation and language detection.
# Question : Implement a Rust program to perform real-time natural language translation and language detection. 
Path to create the file : `54a0qe/xC6lTa.rs`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Sarthakcried**
# 📑 DESCRIPTION

Issue Number : #51
### ❓ What has been changed : 

Fixes #51

Fixes #51

### CODE REVIEW

**Comment by Sarthakcried** [comment]
!check

**Comment by Sarthakcried** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
