### PR TITLE
[Shell] Img to video Closes#113

### LINKED ISSUE #113: [Shell] [hard] Write a script that converts a series of images in a directory to a video.
# Question : Write a script that converts a series of images in a directory to a video. 
Path to create the file : `annqUj/VpplEl.sh`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by notpritam**
# 📑 DESCRIPTION

Issue Number : #113 

### ❓ What has been changed :  
Created : - annqUj/VpplEl.sh

Fixes #113

### CODE REVIEW

**Comment by notpritam** [comment]
!check

**Comment by notpritam** [comment]
!check

**Comment by notpritam** [comment]
!check

**Comment by notpritam** [comment]
!check

**Comment by notpritam** [comment]
!check

**Comment by CodingWithHardik** [comment]
complete task 2

**Comment by CodingWithHardik** [comment]
i am closing this issue msg on WhatsApp I will re-open this issue

**Pull request closed without merging**
