### PR TITLE
Create csaOf4.cs

### LINKED ISSUE #1299: [C#] [easy] Convert a string to lowercase.
# Question : Convert a string to lowercase. 
Path to create the file : `MFfOdV/csaOf4.cs`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by TtgNoob**
# 📑 DESCRIPTION

Issue Number : #1299 
### ❓ What has been changed : 

Fixes #1299

Fixes #1299

### CODE REVIEW

**Comment by TtgNoob** [comment]
!check

**Comment by TtgNoob** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
