### PR TITLE
Create 1H1PN6.js

### LINKED ISSUE #344: [JavaScript] [medium] Write a JavaScript program to implement a basic suffix tree data structure for efficient string matching.
# Question : Write a JavaScript program to implement a basic suffix tree data structure for efficient string matching. 
Path to create the file : `MV25Hf/1H1PN6.js`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Sanketgadekar31**
# 📑 DESCRIPTION

Issue Number : #344
### ❓ What has been changed : 

Fixes #344

Fixes #344

### CODE REVIEW

**Comment by Sanketgadekar31** [comment]
!check

**Comment by Sanketgadekar31** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
