### PR TITLE
Create jEiDld.cs

### LINKED ISSUE #120: [C#] [hard] Implement a program for real-time speech synthesis.
# Question : Implement a program for real-time speech synthesis. 
Path to create the file : `oB0OBu/jEiDld.cs`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Piyusss**
# 📑 DESCRIPTION

Issue Number : #120
### ❓ What has been changed : 

Fixes #120

Fixes #120

### CODE REVIEW

**Comment by Piyusss** [comment]
!check

**Comment by Piyusss** [comment]
!check

**Comment by Piyusss** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
