### PR TITLE
Create 4dr2Ob.java

### LINKED ISSUE #398: [Java] [very_easy] Create a class called 'Circle' that implements the 'Drawable' interface.
# Question : Create a class called 'Circle' that implements the 'Drawable' interface. 
Path to create the file : `7yBzY6/4dr2Ob.java`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by khushisaxena17**
# 📑 DESCRIPTION

Issue Number : #398
### ❓ What has been changed : 

Fixes #398

Fixes #398

### CODE REVIEW

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Comment by khushisaxena17** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
