### PR TITLE
Create FTPqo4.rb

### LINKED ISSUE #354: [Ruby] [easy] Generate a Fibonacci sequence of n terms.
# Question : Generate a Fibonacci sequence of n terms. 
Path to create the file : `UhqonK/FTPqo4.rb`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by souvikpramanikgit**
# 📑 DESCRIPTION

Issue Number : #354
### ❓ What has been changed : 

Fixes #354

Fixes #354

### CODE REVIEW

**Comment by souvikpramanikgit** [comment]
!check

**Comment by souvikpramanikgit** [comment]
!check

**Comment by souvikpramanikgit** [comment]
!check

**Comment by souvikpramanikgit** [comment]
!check

**Comment by souvikpramanikgit** [comment]
!check

**Comment by souvikpramanikgit** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
