### PR TITLE
Created hexadecimal color code validator

### LINKED ISSUE #251: [Ruby] [easy] Check if a string is a valid hexadecimal color code.
# Question : Check if a string is a valid hexadecimal color code. 
Path to create the file : `868eCt/4Y5HDb.rb`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by fvaysh**
📑 DESCRIPTION
This PR is linked to #251 
❓ What has been changed : 
Created a folder and a file in it  - 868eCt/4Y5HDb.rb
Added a Ruby code to check if a particular string as in input with "#(CODE)" is a valid hexadecimal color code or not.

Fixes #251

### CODE REVIEW

**Comment by fvaysh** [comment]
This issue is in reference to #251 , please review and merge it under hacktoberfest2023

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
