### PR TITLE
Create JcMnNW.sh

### LINKED ISSUE #355: [Shell] [hard] Write a script that generates a report of file permissions for all files and directories within a specified path.
# Question : Write a script that generates a report of file permissions for all files and directories within a specified path. 
Path to create the file : `NcE80T/JcMnNW.sh`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Satya2234**
# 📑 DESCRIPTION

Issue Number : #355
### ❓ What has been changed : 

Fixes #355

Fixes #355

### CODE REVIEW

**Comment by Satya2234** [comment]
!check

**Comment by Satya2234** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
