### PR TITLE
Create FAZsE8.c

### LINKED ISSUE #68: [C] [medium] Write a C program to reverse words in a sentence using functions.
# Question : Write a C program to reverse words in a sentence using functions. 
Path to create the file : `J3HBtd/FAZsE8.c`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by biswabismay**
# 📑 DESCRIPTION

Issue Number : #68
### ❓ What has been changed : 

Fixes #68

Fixes #68

### CODE REVIEW

**Comment by biswabismay** [comment]
!check

**Comment by biswabismay** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
