### PR TITLE
Create RzzUDL.go

### LINKED ISSUE #288: [Go] [hard] Write a program that simulates a complex supply chain management system with real-time inventory tracking.
# Question : Write a program that simulates a complex supply chain management system with real-time inventory tracking. 
Path to create the file : `K3Y4Z3/RzzUDL.go`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Sarthakcried**
# 📑 DESCRIPTION

Issue Number : #288
### ❓ What has been changed : 

Fixes #288

Fixes #288

### CODE REVIEW

**Comment by Sarthakcried** [comment]
!check

**Comment by Sarthakcried** [comment]
!check

**Comment by Sarthakcried** [comment]
!check

**Comment by Sarthakcried** [comment]
!check

**Comment by Sarthakcried** [comment]
!check

**Comment by Sarthakcried** [comment]
!check

**Comment by Sarthakcried** [comment]
I have followed CodingwithHardik but still the task 2 is not completing

**Comment by Sarthakcried** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
