### PR TITLE
added function with example #11-issue

### LINKED ISSUE #11: [Python] [easy] Create a function to calculate the sum of all elements in a nested list.
# Question : Create a function to calculate the sum of all elements in a nested list. 
Path to create the file : `K9k3BE/aj46RH.py`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by akadeepesh**
# 📑 DESCRIPTION

Issue Number : #11 
### ❓ What has been changed : 
added function to  calculate the sum of all elements in a nested list

Fixes #11

Fixes #11

### CODE REVIEW

**Comment by akadeepesh** [comment]
!check

**Comment by akadeepesh** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
