### PR TITLE
Create Q4SlQM.c

### LINKED ISSUE #428: [C] [medium] Write a C program to perform quicksort on an array using functions.
# Question : Write a C program to perform quicksort on an array using functions. 
Path to create the file : `gu6U0S/Q4SlQM.c`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by prakhar2347**
# 📑 DESCRIPTION

Issue Number : #428 
### ❓ What has been changed : #428 

Fixes #428

Fixes #428

### CODE REVIEW

**Comment by prakhar2347** [comment]
!check

**Comment by prakhar2347** [comment]
!check

**Comment by prakhar2347** [comment]
!check

**Comment by prakhar2347** [comment]
!check

**Comment by prakhar2347** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
