### PR TITLE
Create J7JNrA.go

### LINKED ISSUE #375: [Go] [medium] Create a Go program that reads data from a weather API and provides current weather conditions based on user input.
# Question : Create a Go program that reads data from a weather API and provides current weather conditions based on user input. 
Path to create the file : `6ca4ZO/J7JNrA.go`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by abhishek22134**
# 📑 DESCRIPTION

Issue Number : #375
### ❓ What has been changed : 

Fixes #375

### CODE REVIEW

**Comment by abhishek22134** [comment]
!check

**Comment by abhishek22134** [comment]
!check

**Comment by abhishek22134** [comment]
!check

**Comment by abhishek22134** [comment]
!check

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
