### PR TITLE
Create a PHP script to validate a credit card number.

### LINKED ISSUE #391: [PHP] [easy] Create a PHP script to validate a credit card number.
# Question : Create a PHP script to validate a credit card number. 
Path to create the file : `K05E8i/1hpT9W.php`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by purnasth**
# 📑 DESCRIPTION

This PR creates a PHP script to validate a credit card number.

Solves Issue Number: #391

# Attachments: 

image

image

Fixes #391

### CODE REVIEW

**Comment by CodingWithHardik** [comment]
Star this repo and comment `!check` to check if the task is completed.

**Comment by purnasth** [comment]
!check

**Comment by purnasth** [comment]
!check

**Comment by purnasth** [comment]
!check

**Comment by purnasth** [comment]
!check

**Comment by purnasth** [comment]
!check

**Comment by purnasth** [comment]
!check

**Comment by purnasth** [comment]
Even though I've already followed @CodingWithHardik, the notice "Seems like you haven't completed Task 2 follow @CodingWithHardik to complete Task 2" appears after I !check every time.

## Attachments 

https://github.com/SourceFusionHub/program/assets/107195487/654db3a6-0448-46a2-915e-014b2c6a13c8

**Comment by purnasth** [comment]
!check

**Comment by purnasth** [comment]
!check

**Comment by purnasth** [comment]
!assign

**Comment by purnasth** [comment]
!check

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Pull request merged**
