### PR TITLE
Solving Issue #144

### LINKED ISSUE #144: [PHP] [easy] Display a random quote from an array of quotes.
# Question : Display a random quote from an array of quotes. 
Path to create the file : `SYNgAF/m9H1Gv.php`

To assign yourself for this issue use `!assign`

### PR DESCRIPTION
**Pull request by Swarno-Coder**
# 📑 DESCRIPTION

Issue Number: #144
### ❓ What has been changed : 
- File created SYNgAF/m9H1Gv.php
- File used to: Question: Display a random quote from an array of quotes.

Fixes #144

Fixes #144

### CODE REVIEW

**Comment by Swarno-Coder** [comment]
!check

**Comment by Swarno-Coder** [comment]
!check

**Comment by Swarno-Coder** [comment]
!check

**Comment by Swarno-Coder** [comment]
!check

**Comment by Swarno-Coder** [comment]
!check

**Comment by CodingWithHardik** [comment]
delete `gs7Cxj/76hMmq.py` this file

**Review by CodingWithHardik — CHANGES_REQUESTED** [review]
delete `gs7Cxj/76hMmq.py` this file

**Review by CodingWithHardik — APPROVED** [review]
good keep it up! 
Follow [Cloud Hustlers](https://www.youtube.com/@CloudHustlers) for more such content

**Comment by CodingWithHardik** [comment]
!accept

**Comment by Swarno-Coder** [comment]
@CodingWithHardik Thank you. It means a lot.

**Pull request merged**
